name: CI
on:
  push:
    branches-ignore:
        - main
jobs:
  yaml_lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: YAML Lint
      uses: ibiqlik/action-yamllint@v0.0.1
      with:
        file_or_dir: .
        config_file: .yamllint.yaml
